import { createClient, SupabaseClient } from '@supabase/supabase-js';

// This module is imported by both the local Express server (src/index.ts)
// and the Cloudflare Worker entrypoint (src/worker.ts). The Worker bundle
// can't include Node-only modules, so this deliberately uses console.*
// instead of the winston-based logger, which pulls in fs/os/etc.
//
// The Node/Express clients below are built lazily (on first use) rather
// than at module load time. In the Workers runtime, merely importing this
// file for its createSupabaseAdmin() factory evaluates this whole module -
// eagerly calling createClient() here with an empty URL (process.env isn't
// populated at Worker module-load time) throws and crashes the Worker
// before any request handler runs, even though the Worker never touches
// these exports.

let _supabaseClient: SupabaseClient | null = null;
let _supabaseAdmin: SupabaseClient | null = null;

/** User-scoped client (anon key) - Node/Express local dev only. */
export function getSupabaseClient(): SupabaseClient {
  if (!_supabaseClient) {
    const url = process.env.SUPABASE_URL || '';
    const key = process.env.SUPABASE_ANON_KEY || '';
    if (!url || !key) {
      console.error('Supabase environment variables not set (SUPABASE_URL / SUPABASE_ANON_KEY)');
    }
    _supabaseClient = createClient(url, key, { auth: { persistSession: false } });
  }
  return _supabaseClient;
}

/** Admin client (service role key) - Node/Express local dev only. */
export function getSupabaseAdmin(): SupabaseClient {
  if (!_supabaseAdmin) {
    const url = process.env.SUPABASE_URL || '';
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
    _supabaseAdmin = serviceKey
      ? createClient(url, serviceKey, { auth: { persistSession: false } })
      : getSupabaseClient();
  }
  return _supabaseAdmin;
}

/**
 * Build a Supabase admin client from explicit credentials. Used by the
 * Cloudflare Workers entrypoint, where secrets arrive per-request via
 * env bindings rather than process.env.
 */
export function createSupabaseAdmin(url: string, serviceRoleKey: string): SupabaseClient {
  return createClient(url, serviceRoleKey, {
    auth: { persistSession: false },
  });
}

/**
 * Initialize Supabase connection
 */
export async function initializeSupabase(): Promise<void> {
  try {
    // Test connection by checking if we can access auth
    const { error } = await getSupabaseClient().auth.getUser();
    if (error && error.status !== 401) {
      // 401 is expected when not authenticated
      throw error;
    }
    console.log('✓ Supabase connected');
  } catch (error) {
    console.error('Failed to connect to Supabase:', error);
    throw error;
  }
}

/**
 * Get a user by ID
 */
export async function getUser(db: SupabaseClient, userId: string): Promise<any> {
  const { data, error } = await db.from('users').select('*').eq('id', userId).maybeSingle();
  if (error) throw error;
  return data;
}

/**
 * Get user by phone number. Returns null when no user exists.
 */
export async function getUserByPhone(db: SupabaseClient, phoneNumber: string): Promise<any> {
  const { data, error } = await db
    .from('users')
    .select('*')
    .eq('phone_number', phoneNumber)
    .maybeSingle();

  if (error) throw error;
  return data;
}

/**
 * Create a new user. `id` is generated by the database default.
 */
export async function createUser(
  db: SupabaseClient,
  userData: {
    phone_number: string;
    email?: string;
    first_name: string;
    last_name: string;
    password_hash: string;
  }
): Promise<any> {
  const { data, error } = await db.from('users').insert([userData]).select().single();
  if (error) throw error;
  return data;
}

/**
 * Get or create wallet for user
 */
export async function getOrCreateWallet(db: SupabaseClient, userId: string): Promise<any> {
  const { data, error } = await db
    .from('wallets')
    .select('*')
    .eq('user_id', userId)
    .maybeSingle();

  if (error) throw error;
  if (data) return data;

  const { data: newWallet, error: createError } = await db
    .from('wallets')
    .insert([
      {
        user_id: userId,
        balance: 0,
        currency: 'MVR',
      },
    ])
    .select()
    .single();

  if (createError) throw createError;
  return newWallet;
}

/**
 * Get wallet balance
 */
export async function getWalletBalance(db: SupabaseClient, userId: string): Promise<number> {
  const wallet = await getOrCreateWallet(db, userId);
  return wallet?.balance || 0;
}

/**
 * Update wallet balance
 */
export async function updateWalletBalance(
  db: SupabaseClient,
  userId: string,
  amount: number,
  operation: 'add' | 'subtract'
): Promise<number> {
  const wallet = await getOrCreateWallet(db, userId);

  const newBalance =
    operation === 'add' ? (wallet.balance || 0) + amount : (wallet.balance || 0) - amount;

  if (newBalance < 0) {
    throw new Error('Insufficient balance');
  }

  const { data, error } = await db
    .from('wallets')
    .update({ balance: newBalance })
    .eq('user_id', userId)
    .select()
    .single();

  if (error) throw error;
  return data.balance;
}

/**
 * Log transaction
 */
export async function logTransaction(
  db: SupabaseClient,
  transaction: {
    wallet_id: string;
    type: string;
    amount: number;
    currency?: string;
    status?: string;
    description?: string;
    reference_number?: string;
  }
): Promise<any> {
  const { data, error } = await db
    .from('transactions')
    .insert([
      {
        ...transaction,
        currency: transaction.currency || 'MVR',
        status: transaction.status || 'COMPLETED',
      },
    ])
    .select()
    .single();

  if (error) throw error;
  return data;
}

export default {
  getSupabaseClient,
  getSupabaseAdmin,
  createSupabaseAdmin,
  initializeSupabase,
  getUser,
  getUserByPhone,
  createUser,
  getOrCreateWallet,
  getWalletBalance,
  updateWalletBalance,
  logTransaction,
};
